version: "3.7"

services:
  dockermvp:
    image: dockermvp:local
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: docker-mvp
    entrypoint: /bin/zsh /code/init.sh
    ports:
      # src:dest (src=port on container, dest=port on host machine)
      - "7741:7740" # Port for Jupyter notwbook
      - "8080:8080" # Map port for airflow webserver
      - "2222:22"   # Map port for openssh
      - "8050:8050" # For dash app
      - "8889:8889" # For jupyter lab
    volumes:
      - type: bind
        source: .
        target: /code
